// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcotkto_SbUDEJ3vKHSuznUK6GAtab6ok',
    appId: '1:1076543723806:web:53ef8a1ce59342fa79110f',
    messagingSenderId: '1076543723806',
    projectId: 'mantravat-intern',
    authDomain: 'mantravat-intern.firebaseapp.com',
    storageBucket: 'mantravat-intern.appspot.com',
    measurementId: 'G-4MN4RYH83Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqxVPB2tFWxB3cNGSSiOUNSnkfn2ofQV0',
    appId: '1:1076543723806:android:ab04971507a595a179110f',
    messagingSenderId: '1076543723806',
    projectId: 'mantravat-intern',
    storageBucket: 'mantravat-intern.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_CEMNX3f1PKQMrCV5u-VcgD94A7aLs60',
    appId: '1:1076543723806:ios:1ee907d6b451d2eb79110f',
    messagingSenderId: '1076543723806',
    projectId: 'mantravat-intern',
    storageBucket: 'mantravat-intern.appspot.com',
    iosClientId: '1076543723806-rgruruelj74872lcg70ulsp4h0upldsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.managementApp',
  );
}
